# Usuário remoto para conexão via SSH
vm_user: ubuntu
# Guardando o valor do IP do servidor Rancher
rancher_server_ip: "{{ hostvars[groups['rancher_master'][0]].ansible_host }}"
# Indicar a url do Rancher
rancher_url: "rancher.homelab.local"
# Indicar a senha do admin do Rancher
admin_password: "Admin123"
# Indicar se o Longhorn deve ser instalado
longhorn_install: true
# Indicar se o Monitoring deve ser instalado
monitoring_install: true
monitoring:
  version: "106.1.2+up69.8.2-rancher.7"
  namespace: "cattle-monitoring-system"
  storageClass: "longhorn"
  grafana:
    admin_password: "Admin123"
    size: "10Gi"
  prometheus:
    retention: "15d"
    size: "20Gi"
  alertmanager:
    size: "2Gi"