---
- name: "[Install GitOps] - Create namespace for ArgoCD"
  kubernetes.core.k8s:
    name: argocd
    state: present
    namespace: argocd

- name: "[Install GitOps] - Install ArgoCD"
  ansible.builtin.shell: >
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  become: true
  changed_when: "'created' in argocd_install.stdout or 'configured' in argocd_install.stdout"
  when: inventory_hostname in groups['rancher_master']
  register: argocd_install

- name: "[Install GitOps] - Wait for ArgoCD pods to be ready"
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: argocd
    label_selectors:
      - app.kubernetes.io/name=argocd-server
  register: argocd_pods
  when: inventory_hostname in groups['rancher_master'] and argocd_install is changed
  until: argocd_pods.resources | length > 0 and argocd_pods.resources[0].status.phase == 'Running'
  retries: 10
  delay: 10

- name: "[Install GitOps] - Create Ingress for ArgoCD"
  kubernetes.core.k8s:
    src: "{{ playbook_dir }}/templates/argocd_ingress.yaml.j2"
    state: present
  register: argocd_ingress
  when: inventory_hostname in groups['rancher_master'] and argocd_install is changed

- name: "[Install GitOps] - Set ArgoCD URL"
  ansible.builtin.set_fact:
    argocd_url: "{{ gitops.url if gitops.url else 'argocd.' + rancher_url }}"
  when: inventory_hostname in groups['rancher_master'] and argocd_install is changed

- name: "[Install GitOps] - Get ArgoCD admin password"
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: argocd
    name: argocd-initial-admin-secret
  register: argocd_secret
  when: inventory_hostname in groups['rancher_master'] and argocd_install is changed

- name: "[Install GitOps] - Decode ArgoCD admin password"
  ansible.builtin.set_fact:
    argocd_admin_password: "{{ argocd_secret.resources[0].data['password'] | b64decode }}"

- name: "[Install GitOps] - Print ArgoCD access information"
  ansible.builtin.debug:
    msg: "ArgoCD is installed at {{ argocd_url }} with admin password: {{ argocd_admin_password }}"
  when: inventory_hostname in groups['rancher_master'] and argocd_install is changed