---
- name: "[Install Monitoring] - Check if HELM is installed"
  ansible.builtin.command: >
    helm version 
  register: helm_version_check
  changed_when: false
  ignore_errors: true

- name: "[Install Monitoring] - install HELM"
  ansible.builtin.shell: >
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  become: true
  when: helm_version_check is failed

- name: "[Install Monitoring] - Add Rancher Monitoring Helm repository and Update"
  kubernetes.core.helm_repository:
    name: rancher-charts
    repo_url: https://charts.rancher.io
    state: present
    force_update: true
  
- name: "[Install Monitoring] - Install Monitoring Stack using Helm"
  kubernetes.core.helm:
    name: rancher-monitoring
    chart_ref: rancher-charts/rancher-monitoring
    namespace: cattle-monitoring-system
    create_namespace: true
    wait: true
    values:
      grafana:
        persistence:
          enabled: true
          storageClassName: "longhorn"
          size: 10Gi