---
- name: "[Install Longhorn] - Add Longhorn Helm repository and Update"
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
    state: present
    force_update: true

- name: "[Install Longhorn] - Longhorn installation"
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    namespace: longhorn-system
    create_namespace: true
    wait: true