---
- name: [Install Monitoring] - Add Rancher Monitoring Helm repository and Update
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    state: present
    force_update: true
  
- name: [Install Monitoring] - Install Monitoring Stack using Helm
  kubernetes.core.helm:
    name: prometheus-operator
    chart_ref: prometheus-community/kube-prometheus-stack
    namespace: cattle-monitoring-system
    create_namespace: true
    wait: true
    values:
      prometheusOperator:
        createCustomResource: true
      grafana:
        enabled: true
      alertmanager:
        enabled: true
      kubeStateMetrics:
        enabled: true
      nodeExporter:
        enabled: true