---
- name: "[Install Monitoring] - Check if HELM is installed"
  ansible.builtin.shell: >
    helm version 
  changed_when: false
  failed_when: false
  ignore_errors: true
  register: helm_version_check

- name: "[Install Monitoring] - install HELM"
  ansible.builtin.shell: >
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  become: true
  when: helm_version_check.rc != 0

- name: "[Install Monitoring] - Create namespace cattle-fleet-system"
  ansible.builtin.shell: >
    kubectl create ns cattle-fleet-system
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: "[Install Monitoring] - Add Rancher Monitoring Helm repository and Update"
  kubernetes.core.helm_repository:
    name: rancher-charts
    repo_url: https://charts.rancher.io
    state: present
    force_update: true

- name: "[Install Monitoring] - Install CRD for Rancher Monitoring"
  kubernetes.core.helm:
    name: rancher-monitoring-crd
    chart_ref: rancher-charts/rancher-monitoring-crd
    namespace: "{{ monitoring.namespace }}"
    create_namespace: true
    chart_version: "{{ monitoring.version }}"
    wait: true
  
- name: "[Install Monitoring] - Install Monitoring Stack using Helm"
  kubernetes.core.helm:
    name: rancher-monitoring
    chart_ref: rancher-charts/rancher-monitoring
    namespace: "{{ monitoring.namespace }}"
    create_namespace: true
    chart_version: "{{ monitoring.version }}"
    wait: true
    values: "{{ lookup('template', 'values_monitoring.yaml.j2') | from_yaml }}"