- name: Disable firewall ufw
  ansible.builtin.systemd:
    name: ufw
    enabled: false
    state: stopped
  become: true

- name: Update all packages
  ansible.builtin.package:
    name: "*"
    state: latest
  become: true
- name: install packages
  ansible.builtin.package:
    name:
      - nfs-common
      - open-iscsi
      - curl
    state: present
  become: true