---
- name: Playbook to install Rancher
  hosts: "{{ target_hosts | default('none') }}"
  remote_user: "{{ vm_user | default('ubuntu') }}"

  roles:
    - role: rancher

  tasks:
    - name: "Print URL Rancher UI"
      ansible.builtin.debug:
        msg: "For access, use the URL: https://{{ rancher_url }}"
      when: inventory_hostname in groups['rancher_master']